config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'calculator' => 'calculations#show'
  post 'calculator' => 'calculations#show'
  resources :lineups

  resources :baseball

end

app/models/game.rb
class Game < ActiveRecord::Base
  # belongs_to :week
  has_many :participations
  has_many :teams,          :through => :participations
  has_many :game_plays
  has_many :players,        :through => :game_plays
  # has_many :fantasy_data

  #-------------------------------------------------
  #    Scopes
  #-------------------------------------------------
  scope :team_and_week, lambda { |team_id, week_number| joins(:teams).where(week: week_number).where(teams: {id: team_id}) }

  #-------------------------------------------------
  #    Instance Methods (Public)
  #-------------------------------------------------
  def team_names
    teams.pluck(:abbreviation)
  end

  def players
    teams.map {|team| team.players}.flatten
  end

end

app/models/game_play.rb
class GamePlay < ActiveRecord::Base
  belongs_to  :game
  belongs_to  :player
  # belongs_to  :team

  #-------------------------------------------------
  #    Scopes
  #-------------------------------------------------
  scope :for_week,                          ->(week_number) { joins(:game).where(games: {week: week_number}) }
  scope :for_position,                      ->(positions)   { joins(:player).where(players: {position: positions}) }
  scope :rotowire_fanduel_projected_value,  ->(minimum)     { where('round(rotowire_fanduel_projected_value, 2) >= ?', minimum.to_f)}
  scope :rotowire_fanduel_projected_points, ->(minimum)     { where('round(rotowire_fanduel_projection_fpts, 2) >= ?', minimum.to_f)}
  scope :fantasy_pros_projected_value,      ->(maxcost)     { where.not(fpros_cost_per_point: 'INF').where('round(fpros_cost_per_point, 0) <= ?', maxcost.to_f)}
  scope :fantasy_pros_projected_points,     ->(minimum)     { where('round(fpros_projected_points, 2) >= ?', minimum.to_f)}

  #-------------------------------------------------
  #    Instance Methods
  #-------------------------------------------------
  
  
end

app/models/lineup.rb
class Lineup < ActiveRecord::Base
  has_many :player_lineups
  has_many :players,        :through => :player_lineups

  #-------------------------------------------------
  #    Scopes
  #-------------------------------------------------
  scope :for_week, ->(week_number) { where(week: week_number) }

end

app/models/participation.rb
class Participation < ActiveRecord::Base
  belongs_to :game
  belongs_to :team
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to  :team
  has_many    :game_plays
  has_many    :games,         :through => :game_plays
  has_many    :player_lineups
  has_many    :lineups,       :through => :player_lineups

  #-------------------------------------------------
  #    Instance Methods (Public)
  #-------------------------------------------------
  def find_ffn_score(week)
    game_plays.for_week(week).first.ffn_standard.to_f.round(2)
  end

  def find_ffn_floor(week)
    game_plays.for_week(week).first.ffn_standard_low.to_f.round(2)
  end

  def find_ffn_ceiling(week)
    game_plays.for_week(week).first.ffn_standard_high.to_f.round(2)
  end

  def find_ffn_downside(week)
    (find_ffn_score(week) - find_ffn_floor(week)).round(2)
  end

  def find_ffn_upside(week)
    (find_ffn_ceiling(week).to_f - find_ffn_score(week)).round(2)
  end

  def find_ffn_ppr(week)
    game_plays.for_week(week).first.ffn_ppr
  end

  def find_ffn_ppr_floor(week)
    game_plays.for_week(week).first.ffn_ppr_low
  end

  def find_ffn_ppr_ceiling(week)
    game_plays.for_week(week).first.ffn_ppr_high
  end

  def find_ffn_ppr_downside(week)
    (find_ffn_ppr(week).to_f - find_ffn_ppr_floor(week).to_f).round(2)
  end

  def find_ffn_ppr_upside(week)
    (find_ffn_ppr_ceiling(week).to_f - find_ffn_ppr(week).to_f).round(2)
  end
end

app/models/player_lineup.rb
class PlayerLineup < ActiveRecord::Base
  belongs_to :player
  belongs_to :lineup
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :participations
  has_many :games,          :through => :participations
  has_many :players
  # has_many :game_plays
end

app/models/week.rb
class Week < ActiveRecord::Base
  # belongs_to :season
  # has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/baseball_controller.rb
class BaseballController < ApplicationController
  def index
    today = Date.today
    @games = GamedayApi::Game.find_by_date(today.year, today.month, today.day)
  end

  def show
    # obviously need to pull all this out into a BaseballGame model
    year = Date.today.year
    month = Date.today.month
    day = Date.today.day
    year = 2014 # remove this after 2015 becomes viable
    game = GamedayApi::FutureLineScore.new
    gid = params[:id]
    game.load_from_id(gid)
    @pitcher_home = GamedayApi::Pitcher.new
    @pitcher_away = GamedayApi::Pitcher.new
    pitcherid = game.home_pitcher.pid
    pitcher_away_id = game.away_pitcher.pid
    @pitcher_home.load_from_year_id(year, pitcherid)
    @pitcher_away.load_from_year_id(year, pitcher_away_id)

    @home_pitcher_fip = @pitcher_home.fip.round(4)
    @away_pitcher_fip = @pitcher_away.fip.round(4)
    @home_team = game.home_team_name
    @away_team = game.away_team_name

    # #maybe instead get batting average for team against current pitcher (hard to do)

    home_team = GamedayApi::Team.new(game.home_team_abbr)
    away_team = GamedayApi::Team.new(game.away_team_abbr)

    previous_game_h = home_team.games_for_date(year, month+1, day-1) #need to check if there was not a game yesterday
    previous_game_a = away_team.games_for_date(year, month+1, day-1) #remove the +1 here after 2015 gets started

    @pitcher_home.load_from_id(previous_game_h[0].gid, pitcherid)
    @pitcher_away.load_from_id(previous_game_a[0].gid, pitcher_away_id)
  end
end

app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController

  def show
    if params[:players]
      week      = params[:week]
      floor     = params[:floor]
      players   = params[:players]
      qbs       = params[:quarterbacks]
      rbs       = params[:running_backs]
      wrs       = params[:receivers]
      tes       = params[:tight_ends]
      ks        = params[:kickers]
      ds        = params[:defenses]
      positions = [qbs, rbs, wrs, tes, ks, ds].compact

      @game_plays = GamePlay.for_week(week).for_position(positions).rotowire_fanduel_projected_value(floor)
      @combos     = @game_plays.combination(players.to_i)
    else
      raise "Pool size too large!" if params[:pool_size].to_i > 50
      raise "Items number is too large!" if params[:items].to_i > 9
      pool        = params[:pool_size].to_i
      items       = params[:items].to_i
      week        = params[:week].to_i
      salary_cap  = params[:salary_cap]
      lineup_size = params[:lineup_size]
      positions   = params[:positions]
      value_floor = params[:floor]
      quantity    = params[:quantity].to_i

      @combinations = SalaryEngine.new(week).build_rotowire_lineups(salary_cap, value_floor, quantity)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/lineups_controller.rb
class LineupsController < ApplicationController

  def index
    @lineups = Lineup.all
    @week_14_lineups = @lineups.for_week(14)
    @week_15_lineups = @lineups.for_week(15)
    @week_16_lineups = @lineups.for_week(16)
    @week_17_lineups = @lineups.for_week(17)
    @week_18_lineups = @lineups.for_week(18)
    @week_19_lineups = @lineups.for_week(19)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/baseball/index.haml
.container
  .row
    .col-md-12.col-sm-12.text-center
      Today's Games
  - @games.each do |game|
    .row
      .col-sm-12.text-center
        = link_to "#{game.gid}", baseball_path(game.gid)

app/views/baseball/show.haml
.container
  .row
    .col-md-12.col-sm-12.text-center
      - if @away_pitcher_fip < @home_pitcher_fip
        %h1= "#{@away_team} (away team) projected starting pitcher #{@pitcher_away.first_name} #{@pitcher_away.last_name} has the advantage over #{@home_team} pitcher #{@pitcher_home.first_name} #{@pitcher_home.last_name}: (#{@away_pitcher_fip} vs #{@home_pitcher_fip})"
      - else
        %h1= "#{@home_team} (home team) projected starting pitcher has the advantage over #{@away_team} pitcher #{@pitcher_away.first_name} #{@pitcher_away.last_name}: (#{@home_pitcher_fip} vs #{@away_pitcher_fip})"
  .row
    .col-sm-12.text-center
      %h1= "#{@pitcher_home.first_name} #{@pitcher_home.last_name}'s overall opponents batting average for this month: #{@pitcher_home.opponent_month.avg}"
      %h1= "#{@pitcher_away.first_name} #{@pitcher_away.last_name}'s overall opponents batting average for this month: #{@pitcher_away.opponent_month.avg}"

app/views/calculations/_fantasy_pros_form.haml
.well
  %h3.text-center= 'Fantasy Pros'
  = form_tag do 
    = label_tag :pool_size, "Pool"
    = text_field_tag :pool_size
    %br
    = label_tag :items, "Items"
    = text_field_tag :items
    %br
    = label_tag :week, "Week"
    = text_field_tag :week
    %br
    = label_tag :salary_cap, "$ Cap"
    = text_field_tag :salary_cap
    %br
    = label_tag :lineup_size, "Lineup"
    = text_field_tag :lineup_size
    %br
    = label_tag :positions, "Positions"
    = text_field_tag :positions
    %br
    = label_tag :floor, "Floor"
    = text_field_tag :floor
    %br
    = label_tag :quantity, "Number"
    = text_field_tag :quantity
    %br
    %br
    .text-right= submit_tag "Build Lineup"

app/views/calculations/_numberfire_form.haml
.well
  %h3.text-center= 'NumberFire'
  = form_tag do 
    = label_tag :pool_size, "Pool"
    = text_field_tag :pool_size
    %br
    = label_tag :items, "Items"
    = text_field_tag :items
    %br
    = label_tag :week, "Week"
    = text_field_tag :week
    %br
    = label_tag :salary_cap, "Salary"
    = text_field_tag :salary_cap
    %br
    = label_tag :lineup_size, "Lineup"
    = text_field_tag :lineup_size
    %br
    = label_tag :positions, "Positions"
    = text_field_tag :positions
    %br
    = label_tag :floor, "Floor"
    = text_field_tag :floor
    %br
    = label_tag :quantity, "Number"
    = text_field_tag :quantity
    %br
    %br
    .text-right= submit_tag "Build Lineup"

app/views/calculations/_rotowire_form.haml
.well
  %h3.text-center= 'Rotowire'
  = form_tag do 
    = label_tag :week, "Week"
    = text_field_tag :week
    %br
    = label_tag :salary_cap, "Salary"
    = text_field_tag :salary_cap
    %br
    = label_tag :lineup_size, "Lineup"
    = text_field_tag :lineup_size
    %br
    = label_tag :positions, "Positions"
    = text_field_tag :positions
    %br
    = label_tag :floor, "Floor"
    = text_field_tag :floor
    %br
    = label_tag :quantity, "Number"
    = text_field_tag :quantity
    %br
    %br
    .text-right= submit_tag "Build Lineup"

app/views/calculations/_rotowire_pool_calculator.haml
.well
  = form_tag do 
    = label_tag :pool_size, "Pool"
    = text_field_tag :pool_size
    %br
    = label_tag :players, "Players"
    = text_field_tag :players
    %br
    = label_tag :week, "Week"
    = text_field_tag :week
    %br
    = label_tag :floor, "Floor"
    = text_field_tag :floor
    %br
    = label_tag :quarterbacks, 'QB'
    = check_box_tag :quarterbacks, 'QB'
    = label_tag :running_backs, 'RB'
    = check_box_tag :running_backs, 'RB'
    = label_tag :receivers, 'WR'
    = check_box_tag :receivers, 'WR'
    = label_tag :tight_ends, 'TE'
    = check_box_tag :tight_ends, 'TE'
    = label_tag :kickers, 'K'
    = check_box_tag :kickers, 'K'
    = label_tag :defenses, 'D'
    = check_box_tag :defenses, 'D'
    %br
    %br
    .text-right= submit_tag "Calculate"

app/views/calculations/_spreadsheet_sports_form.haml
.well
  %h3.text-center= 'Spreadsheet Sports'
  = form_tag do 
    = label_tag :pool_size, "Pool"
    = text_field_tag :pool_size
    %br
    = label_tag :items, "Items"
    = text_field_tag :items
    %br
    = label_tag :week, "Week"
    = text_field_tag :week
    %br
    = label_tag :salary_cap, "$ Cap"
    = text_field_tag :salary_cap
    %br
    = label_tag :lineup_size, "Lineup"
    = text_field_tag :lineup_size
    %br
    = label_tag :positions, "Positions"
    = text_field_tag :positions
    %br
    = label_tag :floor, "Floor"
    = text_field_tag :floor
    %br
    = label_tag :quantity, "Number"
    = text_field_tag :quantity
    %br
    %br
    .text-right= submit_tag "Build Lineup"

app/views/calculations/show.haml
.container
  .row
    .col-md-12.col-sm-12
      %h1= 'Calculator'
      .row
        .col-md-3.col-sm-3
          = render 'rotowire_form'
        .col-md-3.col-sm-3
          = render 'fantasy_pros_form'
        .col-md-3.col-sm-3
          = render 'numberfire_form'
        .col-md-3.col-sm-3
          = render 'spreadsheet_sports_form'
      .row
        .col-md-3.col-sm-3
          = render 'rotowire_pool_calculator'
  %hr
  .row
    .col-md-12.col-sm-12
      = "Pool size: "
      %strong= "#{params[:pool_size]}"
      %br
      = "Number of Items: "
      %strong= "#{params[:players]}"
      %br
      = "Week: "
      %strong= "#{params[:week]}"
      %br
      = "Value Floor: "
      %strong= "#{params[:floor]}"
      %br
      = "Number of game plays: "
      %strong= "#{number_with_delimiter @game_plays.count}" if @game_plays
      %br
      = "Number of combos: "
      %strong= "#{number_with_delimiter @combos.count}" if @combos
      %br
      = "Salary Cap: "
      %strong= "#{params[:salary_cap]}"
      %br
      = "Lineup Size: "
      %strong= "#{params[:lineup_size]}"
      %br
      = "Positions: "
      %strong= "#{params[:positions]}"
      %br
      = "Number of Lineups: "
      %strong= "#{params[:quantity]}"
      %br
      = "Number of combinations: "
      %strong= "#{number_with_delimiter @combinations.count}" if @combinations
      %br
      = "Number of Items: "
      %strong= "#{params[:items]}"
      %br
  %br
  .row
    .col-md-12.col-sm-12
      - if @combinations
        - @combinations.map do |combo|
          / = render partial: 'lineups/lineup_panel', collection: combo, as: :lineup
          - combo.map do |game_play|
            = game_play.player.first_name
            = game_play.player.last_name
            %br
          %br

app/views/home/index.haml
.container
  .row
    .col-md-12.col-sm-12.text-center
      %h1= link_to "Football", lineups_path
  .row
    .col-md-12.col-sm-12.text-center
      %h1= link_to "Baseball", baseball_index_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FantasySports</title>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script type='text/javascript'>
    <%= content_for :inline_javascripts %>
  </script>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

</body>
</html>

app/views/lineups/_lineup_panel.haml
.col-md-3.col-sm-3
  .panel.panel-info
    .panel-heading
      %strong
        = "#{lineup.id} - Week #{lineup.week}"
        .pull-right= "#{lineup.source}"
    .panel-body
      .col-md-4.col-sm-4
        .text-muted= "#{lineup.total_projected_points}"
      .col-md-4.col-sm-4
        %strong= "$#{lineup.total_salary}"
      .col-md-4.col-sm-4
        .text-muted= "#{lineup.actual_points}"
        / %br= "#{lineup.players.count} players"
    %table.table.table-striped.table-condensed
      %thead
        %tr.text-lg
          %th= "Name"
          %th= "Pos"
      %tbody
        - lineup.players.each do |player|
          %tr
            %td= "#{player.first_name} #{player.last_name}"
            %td= player.position

app/views/lineups/index.haml
.container
  .row
    .col-md-12.col-sm-12
      %h1= "Fanduel Lineups"
  .row
    .col-md-12.col-sm-12
      %h3.text-right= "Week 15"
      %hr
  .row
    .col-md-12.col-sm-12
      = render partial: 'lineup_panel', collection: @week_15_lineups, as: :lineup
      %br
  .row
    .col-md-12.col-sm-12
      %h3.text-right= "Week 16"
      %hr
  .row
    .col-md-12.col-sm-12
      = render partial: 'lineup_panel', collection: @week_16_lineups, as: :lineup
      %br
  .row
    .col-md-12.col-sm-12
      %h3.text-right= "Week 17"
      %hr
  .row
    .col-md-12.col-sm-12
      = render partial: 'lineup_panel', collection: @week_17_lineups, as: :lineup
      %br
  .row
    .col-md-12.col-sm-12
      %h3.text-right= "Week 18"
      %hr
  .row
    .col-md-12.col-sm-12
      = render partial: 'lineup_panel', collection: @week_18_lineups, as: :lineup
      %br
  .row
    .col-md-12.col-sm-12
      %h3.text-right= "Week 19"
      %hr
  .row
    .col-md-12.col-sm-12
      = render partial: 'lineup_panel', collection: @week_19_lineups, as: :lineup
      %br
  .row
    .col-md-12.col-sm-12
      %hr
      %br